app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

api:
    resource: '.'
    type: 'api_platform'
    prefix: '/api' # Optional
