services:
    app.event_listener.game.unique_named_player_name_per_play:
        class: AppBundle\EventListener\Game\UniqueNamedPlayerNamePerPlayListener
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    app.event_listener.game.player_score:
        class: AppBundle\EventListener\Game\PlayerScoreListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preRemove }
